### ISSUE TITLE
Packaging the extension

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/SlicerRadiomics#10]
@fedorov, can you describe the current  issues with the packaging of the extension here?
@jcfr, do you have an idea how long it might take to fix this issue?

**Comment by fedorov** [comment]
When SlicerRadiomics is built, python install is properly invoked for all of the packages, but the packages are installed into the Slicer build tree, NOT the extension build tree. As a result, when the extension is packaged from the content of the extension build tree, all of the installed python packages are missing. As I understand from @jcfr, he identified a solution based on passing a flag to python install that specifies the destination location for the installed packages, but has not implemented it yet. This is a bug in Slicer cmake scripts managing extension build.

Based on the discussion last week, @jcfr estimated his time needed to implement this bug fix is 1-2 days of work.

**Comment by fedorov** [comment]
@jcfr does it make sense to add SlicerRadiomics extension anyway, so that whenever the core issues are resolved, we can quickly test the extension functionality?

**Comment by fedorov** [comment]
xref #13

**Comment by fedorov** [comment]
Should be resolved by #13

**Comment by fedorov** [comment]
@jcfr testing with today's nightly, SlicerRadiomics python dependencies are installed:

```
$ ls /Applications/Slicer.app/Contents/Extensions-25996/SlicerRadiomics/lib/python2.7/site-packages
PyWavelets-0.5.2.dist-info                  docopt.py                                   pyradiomics-1.1.1.post73+g9e1e847.dist-info yaml
PyYAML-3.12.dist-info                       docopt.pyc                                  python_dateutil-2.6.0.dist-info
dateutil                                    pykwalify                                   pywt
docopt-0.6.2.dist-info                      pykwalify-1.6.0.dist-info                   radiomics
```

but `import radiomics` fails.

**Comment by fedorov** [comment]
Error:
```
>>> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/Extensions-25996/SlicerRadiomics/lib/Slicer-4.7/qt-scripted-modules/SlicerRadiomics.py", line 5, in <module>
    import radiomics
ImportError: No module named radiomics
```

**Comment by fedorov** [comment]
Superseded by #18
