### ISSUE TITLE
Add progress reporting and cancel option

### ISSUE THREAD

**Issue by pieper** [Radiomics/SlicerRadiomics#21]
When the segmentation is large computation can take a long time and the application hangs with no feedback to the user.

Even as [we optimize the implementation in #256](https://github.com/Radiomics/pyradiomics/issues/256) there will always be situations that require progress reporting.

This may be challenging with the current design, because all computation is done in the main thread without progress events no mechanisms to abort a computation.  That is, [the ITK code to compute Feret diameter is a tight loop](https://github.com/InsightSoftwareConsortium/ITK/blob/9543d93dc85db3d67c6085664cffc08d946d2da2/Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx#L390-L462) and [our proposed replacement cmatrices code](https://github.com/Radiomics/pyradiomics/pull/257/files) follows the same pattern as a single python call that enters a tight C loop.

I suggest we follow [the threading pattern in SimpleFilters](https://github.com/SimpleITK/SlicerSimpleFilters/blob/0e0648faeea0b3cbb8c27a93be0d95253ce13b98/SimpleFilters/SimpleFilters.py#L344-L525).

**Comment by fedorov** [comment]
Makes sense, I agree.

**Comment by JoostJM** [comment]
Regelar segment-based extraction has sufficient speed that progress reporting is not necessary.

Currently, SlicerRadiomics is used via a CLI interface, allowing multithreaded use, increasing responsivity during long-running processes. For this, a form of status updates is provided as ["." printed on the same line](https://github.com/Radiomics/SlicerRadiomics/blob/master/SlicerRadiomics/SlicerRadiomics.py#L574).
