### ISSUE TITLE
Extend user interface for customization

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/SlicerRadiomics#25]
Currently, customization of the extraction is very limited in SlicerRadiomics. Moreover, Yaml parsing using PyYaml doesn't work currently on windows (see #23), which means SlicerRadiomics cannot use the parameterfile.

This issue is created to make a list of GUI elements that should be made to expose the most important customization features of PyRadiomics.

Current suggestions:
- Resampling
- Image normalization
- Filters (including Sigma values for LoG filter)

cc @Radiomics/developers

**Comment by fedorov** [comment]
Also need to add wavelets, see [this post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pyradiomics/dsNolPItBBM) from a confused user ...

**Comment by JoostJM** [comment]
Addressed by #26 and #36

**Comment by JoostJM** [comment]
Fixed by #36
