### ISSUE TITLE
can not find this extension in latest nightly build of slicer

### ISSUE THREAD

**Issue by jxjz** [Radiomics/SlicerRadiomics#42]
Hello,

i have installed the latest nightly build of 3D slicer (Version 4.5.0-1 r24735) and searched for this extension, but no results were found. A local build is the only way to use it in windows? thanks for the answer!

Best,
Lei

**Comment by pieper** [comment]
Hi Lei -

The most recent builds are version 4.9.0 revision 26891 built 2018-02-07 (see http://download.slicer.org/).  You should be able to install SlicerRadiomics for either of those versions.

Just to let you know we have been making some changes related to #38 and #21 so things are currently a bit broken and may be unstable for the next few days.

-Steve

**Comment by pieper** [comment]
As a follow up I just tried the latest nightly on windows and the Radiomics module works as expected.  It's the mac version that's broken (#43).
