### ISSUE TITLE
How to use SLicerRadiomics

### ISSUE THREAD

**Issue by durgeshkdwivedi** [Radiomics/SlicerRadiomics#47]
Hello,
I'm a beginner at pyRadiomics. I've installed radiomics module in the slicer. 
The steps I used for the feature extraction:

Imported the 2D Dicom image (one slice) for the test. 
Drew an ROI on the tumor (label)
Open the module Radiomics in the slicer.
Select All features, apply
Export as a table. 118 features were extracted.

Am I doing it correctly? If the above method is wrong, can anyone guide me through this? Also, is there any way to export the table from the slicer as a CSV file?
 I would really appreciate the help!

Thanks,
Durgesh

**Comment by pieper** [comment]
Yes, that sounds correct - see the PyRadiomics documentation for more info on the config settings:

https://pyradiomics.readthedocs.io/en/latest/index.html

> Also, is there any way to export the table from the slicer as a CSV file?

Yes, just do File->Save and pick the table or you can copy-paste from the table in Slicer.
