### ISSUE TITLE
Add a debug mode option

### ISSUE THREAD

**Issue by pieper** [Radiomics/SlicerRadiomics#5]
To make it easier to debug and to file issues, add a gui option to run in verbose debugging mode.

**Comment by JoostJM** [comment]
@pieper, you mentioned that slicer had something similar in the way of storing a debug log for error/issue reporting. Is there a specific way Slicer goes about this? Otherwise I could add a simple option which uses the logging already present in PyRadiomics, supplemented with some logging in the slicer extension.

**Comment by pieper** [comment]
Hi Joost -

In Slicer we use the python logging package and then have a Help->Report a
Bug menu that brings up this dialog.

So I was thinking that since pyradiomics uses the same package it would be
easy to expose the log level options to the GUI and easily capture the
results.

-Steve


[image: Inline image 1]

**Comment by JoostJM** [comment]
@pieper Sounds great! I'll look into it.

**Comment by fedorov** [comment]
I would vote for saving pyradiomics log into a separate file as initially suggested (or do this in addition to logging to the Slicer log). The way Slicer logging works, it exposes logging that comes from different sources, and the result is log messages that are NOT ordered by time. It can be extremely misleading and difficult to browse those messages.

**Comment by pieper** [comment]
@fedorov the point is not to replace the pyradiomics logging, but to
provide the gui tools for SlicerRadiomics.  It's a good idea to have a
separate log just for the pyradiomics use and even have a gui option in the
module to enable it.

**Comment by fedorov** [comment]
We are all on the same page then!

**Comment by fedorov** [comment]
@JoostJM since you self-assigned this issue, can you let me know if you plan to just add the log mode to pyradiomics, or you want to implement everything including UI elements to expose this in SlicerRadiomics?

**Comment by JoostJM** [comment]
@fedorov, the main reason I assigned it to myself is to update the logging of pyradiomics and add some log messages in slicerradiomics. If you want to implement the UI elements to expose this functionality, I'd greatly appreciate your input.

**Comment by JoostJM** [comment]
I added a simple checkbox in the UI to enable debug logging. If enabled, it now stores the log in the user's root folder. This location is also displayed in the tooltip over this textbox.

**Comment by JoostJM** [comment]
Resolved by #8
