### ISSUE TITLE
I couldn't find the Radiomics in the 3D Slicer extensions manager

### ISSUE THREAD

**Issue by jcnils** [Radiomics/SlicerRadiomics#50]
I don't know if I did something wrong, or if there any dependency missing. But I couldn't find the Radiomics in the 3D Slicer extensions manager.

I tried the search mode in All, and looking for it into the Informatics category.

I am using windows 10, and tried using stable(4.10) and nightly (4.11)

**Comment by pieper** [comment]
There are some unresolved build issues currently on windows, but it is available for linux and mac, in case that helps.

http://slicer.cdash.org/viewBuildError.php?buildid=1417242

**Comment by jcnils** [comment]
Thank you @pieper, linux might help for now. 
I will boot linux while keeping an eye for updates, the lab where the researchers use 3D Slicer is windows only :(

**Comment by pieper** [comment]
@fedorov @JoostJM @jcfr Any ideas about why SlicerRadiomics build is failing on windows?

**Comment by fedorov** [comment]
@jcnils I am reopening this, since the underlying issue has not been resolved.

**Comment by JoostJM** [comment]
@pieper, I just took a quick look at it, and it appears to be that it is [unable to build PyWavelets](http://slicer.cdash.org/buildSummary.php?buildid=1421352) (_dwt.pyd is part of PyWavelets). I will investigate, but I think we may be able to fix this by using a specific PyWavelets version.

**Comment by pieper** [comment]
Thanks for investigating @JoostJM - I hope using a specific version of PyWavelets solves the problem.

**Comment by fedorov** [comment]
Right, the question remains why pywavelets stopped building. In any case, using a fixed version of pywavelets makes a lot of sense.

**Comment by lassoan** [comment]
Slicer uses numpy 1.13.1, while [pywavelet needs numpy >1.9.1](https://github.com/PyWavelets/pywt/blob/master/setup.py#L418), so maybe it is not related to numpy.

**Comment by kevin-why** [comment]
I couldn't find the Radiomics in the 3D Slicer extensions manager either，（ in windows），is there another way to package the extension and install the extension from file？ or the bug has been fixed ？

**Comment by lassoan** [comment]
The issue is still open, which means it has not been resolved yet.

@pieper @fedorov Would it be possible to disable wavelet-based features until this gets resolved?

An option to solve this would be to use wavelets available in VTK or ITK instead (there is at least a IsotropicWavelets remote module in ITK).

**Comment by fedorov** [comment]
@JoostJM is the lead on this project, we should discuss with him. I agree it makes sense to disable wavelets until this is resolved.

@lassoan can you reproduce this issue with a local build? I don't even have a Slicer build set up on Windows that I can access to investigate this.

**Comment by lassoan** [comment]
Yes, I can reproduce it. It is very hard to debug this, as it uses python scripts to create temporary build files that immediately disappear after the build is finished. I don't even know where can I find the Python file that I could change to prevent deleting of the build files so that I can investigate further.

Since pywavelets only supports 2D wavelets anyway, I'm not sure if it is worth the time investigating it.

**Comment by pieper** [comment]
+1 for disabling wavelets, at least on Windows, until this can be nailed down.  There are lots of other features people would want to calculated and we've heard from a lot of users looking for this extension on windows.

**Comment by JoostJM** [comment]
I'll disable wavelets for now.

@lassoan, In PyRadiomics, we apply 3D wavelets by applying filters sequentially in row-column-slice.

Still, I'm really interested in the ITK/VTK implementation, it certainly warrants investigation into if this is easily implementable in PyRadiomics.

**Comment by JoostJM** [comment]
Short update, I now forced PyWavelet version to 1.0.0, which was released on august 31st, this year. Hopefully this fixes the build.

Looking at the release notes, it may be possible that this will fail as well, as complex number support was added in version 1.0.0. If it fails, I'll revert to the version before that (0.5.2).

**Comment by fedorov** [comment]
It is now failing on all platforms, but it looks like a completely different issue: 
http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=radiomics

![image](https://user-images.githubusercontent.com/313942/48421301-334b0f80-e72a-11e8-9d08-7dfd63937496.png)

I will join the Slicer hangout today with the hope to get attention of the folks maintaining the dashboard.

**Comment by jcfr** [comment]
Hi,

I am out at a conference today and we will have a look later.

It seems the extensions server is getting overloaded and it will be time to
plan for transitioning away to the new Girder based system.

Note that the backend is ready and we still need to finalize the frontend.

Thanks
Jc

**Comment by fedorov** [comment]
Thanks JC, this would be great.

Do you have any ideas about the earlier failure as discussed in this issue and in https://discourse.slicer.org/t/radiomics-extension-build-errors-on-windows/4616?

Based on the current errors, do you know if the earlier issue was resolved, or the failure we observe now is happening earlier in the build process?

**Comment by jcfr** [comment]
The build completed on linux, macOS and Windows. This is confirmed by the dashboard (it only reports a failure to upload and no build error) and also by running the build on the build machine:

For example, here is the output running the windows build locally:

![image](https://user-images.githubusercontent.com/219043/48422308-642c4400-e72c-11e8-9f2b-1ee091438520.png)

>  the extensions server is getting overloaded

To clarify, our monitoring confirm this, I have been getting message from our nagios probe and as a short term solution, I just asked our sysadmin to increase the memory associated with the server.

**Comment by fedorov** [comment]
@jcnils  @kevin-why the extension should now be available on all platforms: http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=radiomics

**Comment by emanradiology** [comment]
if I install an older version of 3D slicer, will radiomics extension work?

**Comment by JoostJM** [comment]
@emanradiology, depends on the version. If it is available in the extensions manager there is a high chance it will work. Beware however that this may use an older version of PyRadiomics (for differences between versions, see the [release notes](https://pyradiomics.readthedocs.io/en/latest/changes.html))

What version of Slicer are you planning to use?

**Comment by JoostJM** [comment]
To check the version of PyRadiomics installed, type the following in the python interactor in slicer:
```
import radiomics
radiomics.__version__
```
