### ISSUE TITLE
SlicerRadiomics extension not available for Slicer 4.11.0 on Mac OS

### ISSUE THREAD

**Issue by warkentinmatt** [Radiomics/SlicerRadiomics#55]
Any idea why the SlicerRadiomics extension isn't available for installation in the Extensions Manager on Slicer for the current nightly build version?

Previously I was using an older build; decided to upgrade to the nightly build of Slicer 4.11.0 and the extension is not available any longer.

I am on a Macbook Pro with Mojave 10.14.4.

Thanks for your help.

**Comment by fedorov** [comment]
Slicer is transitioning to python 3, and I am not sure all issues have been sorted out.

The actual build error is here: http://slicer.cdash.org/viewBuildError.php?buildid=1591412

cc: @jcfr 

![image](https://user-images.githubusercontent.com/313942/57898494-519fde00-7827-11e9-83c4-01e546b5212c.png)

**Comment by warkentinmatt** [comment]
@fedorov Thanks for the reply. What sort of timeline might one expect for this to be resolved? Days? Weeks? Months?

I have noticed several other extensions are no longer available in Slicer 4.11.0 (e.g. SlicerCIP). Do extensions ever get archived or are they likely be suffering the same fate (i.e. python build errors)? 

I've only done some cursory looking into this, but is there an easy way to tell which Slicer build versions are still Python 2.7? I guess I should downgrade my Slicer to the most recent Python 2.7 based Slicer to ensure these extensions will be available.

**Comment by fedorov** [comment]
@warkentinmatt I do not have the answers to your questions, although all of them are very reasonable. Your best bet is to find the latest version of Slicer 4.11 and extensions before they were broken by python 3, but I do not know how to do that efficiently. I recommend you post your questions and concerns to the Slicer forum: https://discourse.slicer.org/latest.

I am assuming 4.10 is not an option for you, right?

**Comment by warkentinmatt** [comment]
@fedorov Thanks. I have now created an account for the Slicer forum. I've read my fair share of threads, it's about time I join, anyway.

I am not opposed to using Slicer 4.10. Up until today I was still using 4.8.1; I figured it was time to upgrade so I went right to the nightly build version. In hindsight, perhaps it was a bad idea to skip over the stable release. But I think it would be perfectly reasonable to use 4.10.

**Comment by jcfr** [comment]
This is seems quite easy to address. If I haven't followed up, ping me
again in few days.

**Comment by JoostJM** [comment]
Hi all,

I ran into issues like this before. The current one is located in the PyRadiomics setup.py script, where it is reading the README.md file as the long_description (used for PyPi distribution).

However, the reading just uses default encoding and in some cases this is apparently `ascii`, which fails on a special hyphen located in the readme file. I've updated PyRadiomics to explicitly decode using `utf-8`, which can handle the special hyphen.

I've decided not to update the hyphen, as these slip in sometimes anyway and I thought it better to use a build system that can cope with this.

**Comment by JoostJM** [comment]
This commit contains the fix: Radiomics/pyradiomics@fab347b

**Comment by warkentinmatt** [comment]
@JoostJM Thanks for the update. I assume it will still take some time before this change leads to the SlicerRadiomics extension becoming available again?

**Comment by JoostJM** [comment]
@warkentinmatt Yes, it will be incorporated in the next nightly build (so tomorrow it should be available I think)
