### ISSUE TITLE
Feature calculation failed on windows

### ISSUE THREAD

**Issue by chengjianhong** [Radiomics/SlicerRadiomics#56]
Hi, I install the slicerRadiomics on 3D Slicer by extensions manager. But it occurs the following errors when I use it to extract the brain tumor features. 

> Feature calculation failed.
> Feature calculation failed.
> Traceback (most recent call last):
>   File "C:/Users/15526/AppData/Roaming/NA-MIC/Extensions-27931/SlicerRadiomics/lib/Slicer-4.10/qt-scripted-modules/SlicerRadiomics.py", line 405, in onApplyButton
>     self.onFinished)
>   File "C:/Users/15526/AppData/Roaming/NA-MIC/Extensions-27931/SlicerRadiomics/lib/Slicer-4.10/qt-scripted-modules/SlicerRadiomics.py", line 735, in runCLI
>     self.runCLIWithParameterFile(imageNode, maskNode, tableNode, parameterFile, callback)
>   File "C:/Users/15526/AppData/Roaming/NA-MIC/Extensions-27931/SlicerRadiomics/lib/Slicer-4.10/qt-scripted-modules/SlicerRadiomics.py", line 773, in runCLIWithParameterFile
>     self._startCLI(firstRun=True)
>   File "C:/Users/15526/AppData/Roaming/NA-MIC/Extensions-27931/SlicerRadiomics/lib/Slicer-4.10/qt-scripted-modules/SlicerRadiomics.py", line 531, in _startCLI
>     labelName, labelNode, label_idx, imageNode = self._labelGenerators.__next__()
> AttributeError: 'itertools.chain' object has no attribute '__next__'

**Comment by JoostJM** [comment]
Hi, this is a duplicate issue, which is addressed in [the PyRadiomics forum](https://groups.google.com/d/msg/pyradiomics/YH_HlZYxI48/9mwQYBQ_AwAJ).

Short answer: due to 3D Slicer's transition to Python 3. The bug has already been fixed (36e0965), but requires you to install a newer nightly build.

**Comment by jamesobutler** [comment]
I believe https://github.com/Radiomics/SlicerRadiomics/commit/5fedf5b724f5303b920936266f8d18de922e0d28 has fixed this issue so this can be closed.
