### ISSUE TITLE
Resampling and LoG filtering fail when done at the same time.

### ISSUE THREAD

**Issue by ghost** [Radiomics/SlicerRadiomics#59]
When I try to extract features using resampling and LoG filtering, I cannot get values for the filtered images. However, when I try to use only LoG filtering, there is no problem.

**Comment by JoostJM** [comment]
@drburakkocak My apologies for the late reply. Which version of slicer are you using? can you share the slicer log detailing this error (help > report a bug)?

**Comment by JoostJM** [comment]
Stale issue.
