### ISSUE TITLE
Radiomics does not work in latest stable release of Slicer

### ISSUE THREAD

**Issue by iboeth** [Radiomics/SlicerRadiomics#62]
Excuse my question, but I really do not know what to do. 

As you mentioned on GitHub-Website, Radiomics should be installed on 3D-Slicer Version 4.13 (unstable). 
I followed your description, but it is not possible installing any extension. 
Additionally, DICOM-Data cannot be downloaded in 3D-Slicer, because "unfortunately, this request module is not available in this Slicer session". 
Because of that I tried installing 3D-Slicer Verion 4.11, but I just can install "RadiomicsCLI", which works differently, as I noticed. 

I have a Macbook (macOS Catalina, Version 10.15.7) and would be very pleasant for your help!

**Comment by fedorov** [comment]
Sorry, the instructions are lagging behind the changing situation ... Can you try with the stable version?

**Comment by fedorov** [comment]
I've just tested latest stable on mac, and it is broken. Let me look into this.

![image](https://user-images.githubusercontent.com/313942/97216862-cf964180-179c-11eb-8f51-65ec550b2ea6.png)

**Comment by iboeth** [comment]
The stable version does not allow me extracting my "Segmentations", painted in the tumors.

**Comment by iboeth** [comment]
Thanks for your feedback. I would be happy if you would find the mistake!

**Comment by fedorov** [comment]
I don't know why this is happening, but some dependency packages are not available. Can you try opening python console 

![image](https://user-images.githubusercontent.com/313942/97217600-ed17db00-179d-11eb-90cd-68ee026b2669.png)

and then running the following commands in the console:
```shell
slicer.util.pip_install('pywavelets')
slicer.util.pip_install('python-dateutil')
```

and then try to use the module again after restarting Slicer (stable version)?

**Comment by iboeth** [comment]
![EDAD7877-E1D2-4D08-8E9D-89DF18D3D4BC](https://user-images.githubusercontent.com/73494986/97218119-89ef6e00-17c8-11eb-9eac-c5c84286e598.jpeg)
When I opened python console, this appears and I cannot follow your instructions...

**Comment by fedorov** [comment]
yes - can paste these two lines, one at a time, into that window, and hit "Enter"?

```
slicer.util.pip_install('pywavelets')
slicer.util.pip_install('python-dateutil')
```

**Comment by iboeth** [comment]
Okay, so I did.

**Comment by fedorov** [comment]
Can you now restart Slicer, and see if the module works for you, or let me know what does not work?

**Comment by iboeth** [comment]
![A260D3DE-9A58-4F53-9995-E19D7108AA92](https://user-images.githubusercontent.com/73494986/97219029-be175e80-17c9-11eb-9cf4-1860a65784b7.jpeg)
I restarted and this happened... I´m so sorry for the circumstances...

**Comment by fedorov** [comment]
what messages do you see after you enter `slicer.util.pip_install('pywavelets')` and hit "Enter" in the python console?

**Comment by iboeth** [comment]
![Uploading B07B55E2-C4E5-45D7-BDDE-C0A8039DE0D4.jpeg…]()

**Comment by fedorov** [comment]
@iboeth something went wrong in your upload in the previous post.

**Comment by iboeth** [comment]
![B07B55E2-C4E5-45D7-BDDE-C0A8039DE0D4](https://user-images.githubusercontent.com/73494986/97221367-10a64a00-17cd-11eb-982c-51ba3971b35d.jpeg)

Next try.

**Comment by iboeth** [comment]
I recently starteted 3D-Slicer again and this appeared. Perhaps it helps...
![F6207460-0144-439B-B275-A51C88C9C42E](https://user-images.githubusercontent.com/73494986/97329872-d2199980-1877-11eb-898e-e2b16820531d.jpeg)

**Comment by LiDelight** [comment]
Can I use an old version to avoid this bug?

**Comment by iboeth** [comment]
In my opinion, the "oldest" version is 4.11. 
I restarted this version of 3D-Slicer the last days, but it did not work...

**Comment by LiDelight** [comment]
Try to use python?

**Comment by iboeth** [comment]
Oh! There is no bug today! Thanks!!
But there is still a problem with "extensions", as you see below...

![A99948CF-05FC-4F8C-898B-CBABBE3599EE](https://user-images.githubusercontent.com/73494986/97679414-83494b00-1a95-11eb-81f4-68ed782c73a5.jpeg)

**Comment by LiDelight** [comment]
can it work now?

**Comment by iboeth** [comment]
No, it ist still the same. 
I searched for "Radiomics" and the following happened: 

![6AE8150F-6EEC-4F0F-AF84-925AFF961080](https://user-images.githubusercontent.com/73494986/97704277-62432300-1ab2-11eb-9c64-2ae327d38a02.jpeg)

**Comment by LiDelight** [comment]
Now, can it work?And Is there a solution for the problem?

**Comment by iboeth** [comment]
![9B0D2FA1-9709-464C-9122-2EF6C5FC1B72](https://user-images.githubusercontent.com/73494986/97964835-b0f60300-1db9-11eb-9dc5-8061080b42e6.jpeg)
![5FC4CDE4-688B-45BA-943F-D5431ABFBA20](https://user-images.githubusercontent.com/73494986/97964838-b2273000-1db9-11eb-9c00-e01de4c52fcd.jpeg)
This is the current status. The extention "Radiomics" is also still mapped differently than on the Windows system, but I do not know if that matters...

**Comment by fedorov** [comment]
@LiDelight can you open the python interactor, and run the following two commands there? The issue is in the missing dependency packages, and when I did what I am suggesting here on mac, this resolved the problem for me.
```
slicer.util.pip_install('pywavelets')
slicer.util.pip_install('python-dateutil')
``

**Comment by LiDelight** [comment]
<img width="826" alt="WeChat6d605c15659b243662ff07d878d22707" src="https://user-images.githubusercontent.com/34203375/98012494-20a8d400-1e34-11eb-85e0-685ed9c9908f.png">
()
I think the code is usefull for me. 
slicer.util.pip_install('pywavelets')
slicer.util.pip_install('python-dateutil')
and it has run successfully to install, but!!! then I restart the slicer, there is a so long bug information, and I don't know how to do. crying wuwuuwu~

**Comment by iboeth** [comment]
@fedorov: The Link is usefull for me, too! It seems that my problems are solved!! Thank you so much!!

**Comment by LiDelight** [comment]
OMG, it work, now. I install the stable version of 3D slicer. 淦!

**Comment by iboeth** [comment]
It is me again... 
Using the ruler shows no measure of my ROI. What am I doing wrong? 
![F9BA3F25-CD6C-49A7-B824-2F9303AC35B7](https://user-images.githubusercontent.com/73494986/98448542-066d3f80-212d-11eb-95c5-7e65ce8650e6.jpeg)

**Comment by fedorov** [comment]
Please use Slicer forum for questions about Slicer https://discourse.slicer.org.

**Comment by iboeth** [comment]
Thank you!!

**Comment by fedorov** [comment]
Yesterday I added a fix to check for missing modules and install if they are not present. Please check the latest stable build and let us know if the issue is not resolved.
