### ISSUE TITLE
Install SlicerRadiomics From 3D Slicer on MAC 10.15.5

### ISSUE THREAD

**Issue by iamhyw** [Radiomics/SlicerRadiomics#63]
Hi! I want to use the SlicerRadiomics From 3D Slicer but i can't find the version of MAC.I have tried the methods with source code but failed.Can you provide a install-archive for me？ So I can install from file.THANKS!!!

**Comment by fedorov** [comment]
No, there is no install-archive we can provide. Please monitor this thread for updates on the issue: https://discourse.slicer.org/t/slicer-radiomics-error/14279/4.

**Comment by jcfr** [comment]
macOS extension for the latest stable Slicer release (4.11.20200930) has been re-uploaded.
Please try to uninstall and re-install the extension.

**Comment by iamhyw** [comment]
@jcfr OH! THANKS BRO !!!!!!
